sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - raw
before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "Jeff2310"
  - git config user.email "jeff23101719@gmail.com"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public